import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { 
  Brain, 
  Briefcase, 
  TrendingUp, 
  BookOpen, 
  Pin, 
  Smartphone,
  ArrowUpRight,
  Sparkles,
  Clock,
  Users
} from "lucide-react";
import React from "react";

const Features = () => {
  return (
    <section className="w-full px-6 py-10 bg-gray-50">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <Badge className="bg-gradient-to-r from-blue-100 to-purple-100 text-blue-700 border-blue-200 rounded-full py-1">
            <Sparkles className="h-4 w-4" />
            Features
          </Badge>
          <h2 className="mt-6 text-3xl md:text-4xl font-semibold tracking-tight">
            Everything You Need to{" "}
            <span className="bg-[radial-gradient(circle,#3b82f6_0%,#8b5cf6_100%)] bg-[length:200%_200%] bg-clip-text text-transparent">
              Succeed
            </span>
          </h2>
          <p className="mt-4 text-lg text-gray-600 max-w-2xl mx-auto">
            Comprehensive tools and AI-powered features designed to help you excel in any interview
          </p>
        </div>

        {/* Bento Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {/* Large Feature Card - AI Generation */}
          <div className="lg:col-span-2 bg-gradient-to-br from-purple-50 to-pink-50 border border-purple-200 rounded-xl p-8 relative overflow-hidden">
            <div className="relative z-10">
              <div className="w-14 h-14 bg-gradient-to-r from-purple-500 to-pink-500 rounded-xl flex items-center justify-center mb-6">
                <Brain className="w-7 h-7 text-white" />
              </div>
              <h3 className="text-2xl font-semibold mb-4">AI-Powered Question Generation</h3>
              <p className="text-gray-600 text-lg mb-6">
                Get unlimited, personalized interview questions generated by advanced AI based on your target role and experience level.
              </p>
              <div className="flex gap-3">
                <Badge variant="secondary" className="bg-white/70">Custom Roles</Badge>
                <Badge variant="secondary" className="bg-white/70">Unlimited Questions</Badge>
                <Badge variant="secondary" className="bg-white/70">Real-time Generation</Badge>
              </div>
            </div>
            <div className="absolute top-4 right-4 w-32 h-32 bg-gradient-to-br from-purple-400/20 to-pink-400/20 rounded-full blur-3xl"></div>
          </div>

          {/* Role-Specific Content */}
          <div className="bg-white border rounded-xl p-6 hover:shadow-md transition-shadow">
            <div className="w-12 h-12 bg-blue-50 rounded-lg flex items-center justify-center mb-4">
              <Briefcase className="w-6 h-6 text-blue-600" />
            </div>
            <h3 className="text-xl font-semibold mb-3">Role-Specific Content</h3>
            <p className="text-gray-600 mb-4">
              Questions tailored to specific positions from junior to senior levels.
            </p>
            <Button variant="outline" size="sm" className="w-full">
              Explore Roles <ArrowUpRight className="w-4 h-4 ml-1" />
            </Button>
          </div>

          {/* Adaptive Difficulty */}
          <div className="bg-white border rounded-xl p-6 hover:shadow-md transition-shadow">
            <div className="w-12 h-12 bg-green-50 rounded-lg flex items-center justify-center mb-4">
              <TrendingUp className="w-6 h-6 text-green-600" />
            </div>
            <h3 className="text-xl font-semibold mb-3">Adaptive Difficulty</h3>
            <p className="text-gray-600 mb-4">
              Questions automatically adjust to your experience and performance.
            </p>
            <div className="flex justify-between text-sm text-gray-500">
              <span>Beginner</span>
              <span>→</span>
              <span>Expert</span>
            </div>
          </div>

          {/* Detailed Explanations - Large Card */}
          <div className="lg:col-span-2 bg-gradient-to-br from-orange-50 to-yellow-50 border border-orange-200 rounded-xl p-8 relative">
            <div className="relative z-10">
              <div className="w-14 h-14 bg-gradient-to-r from-orange-500 to-yellow-500 rounded-xl flex items-center justify-center mb-6">
                <BookOpen className="w-7 h-7 text-white" />
              </div>
              <h3 className="text-2xl font-semibold mb-4">Detailed Explanations</h3>
              <p className="text-gray-600 text-lg mb-6">
                Learn from comprehensive explanations, best practices, and expert tips for every question you practice.
              </p>
              <div className="bg-white/70 rounded-lg p-4 border-l-4 border-orange-400">
                <p className="text-sm font-medium text-orange-800">
                  💡 "Explain the difference between REST and GraphQL APIs..."
                </p>
                <p className="text-xs text-orange-600 mt-1">
                  Detailed explanation with code examples and best practices included
                </p>
              </div>
            </div>
            <div className="absolute bottom-4 right-4 w-24 h-24 bg-gradient-to-br from-orange-400/20 to-yellow-400/20 rounded-full blur-2xl"></div>
          </div>

          {/* Session Management */}
          <div className="bg-white border rounded-xl p-6 hover:shadow-md transition-shadow">
            <div className="w-12 h-12 bg-red-50 rounded-lg flex items-center justify-center mb-4">
              <Pin className="w-6 h-6 text-red-600" />
            </div>
            <h3 className="text-xl font-semibold mb-3">Session Management</h3>
            <p className="text-gray-600 mb-4">
              Organize practice sessions and save important questions.
            </p>
            <div className="flex gap-2">
              <div className="w-2 h-2 bg-red-400 rounded-full"></div>
              <div className="w-2 h-2 bg-orange-400 rounded-full"></div>
              <div className="w-2 h-2 bg-green-400 rounded-full"></div>
            </div>
          </div>

          {/* Modern Interface */}
          <div className="bg-white border rounded-xl p-6 hover:shadow-md transition-shadow">
            <div className="w-12 h-12 bg-indigo-50 rounded-lg flex items-center justify-center mb-4">
              <Smartphone className="w-6 h-6 text-indigo-600" />
            </div>
            <h3 className="text-xl font-semibold mb-3">Modern Interface</h3>
            <p className="text-gray-600 mb-4">
              Clean, responsive design that works on all devices.
            </p>
            <div className="flex items-center gap-2 text-sm text-gray-500">
              <Clock className="w-4 h-4" />
              <span>Practice anywhere, anytime</span>
            </div>
          </div>

          {/* Statistics Card */}
          <div className="bg-gradient-to-br from-slate-50 to-gray-50 border rounded-xl p-6">
            <div className="w-12 h-12 bg-slate-100 rounded-lg flex items-center justify-center mb-4">
              <Users className="w-6 h-6 text-slate-600" />
            </div>
            <h3 className="text-xl font-semibold mb-3">Trusted by Professionals</h3>
            <div className="space-y-3">
              <div className="flex justify-between">
                <span className="text-sm text-gray-600">Active Users</span>
                <span className="font-semibold">10,000+</span>
              </div>
              <div className="flex justify-between">
                <span className="text-sm text-gray-600">Questions Generated</span>
                <span className="font-semibold">500K+</span>
              </div>
              <div className="flex justify-between">
                <span className="text-sm text-gray-600">Success Rate</span>
                <span className="font-semibold text-green-600">92%</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Features;